config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
  resources :goals
  
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :name, :user, presence: true
  validates :privacy, :completion, inclusion: { in: [true, false] }
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true}
  
  has_many :goals
  
  before_validation do
    ensure_session_token
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.generate_session_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def self.find_by_credentials(username, password)

    found_user = User.find_by_username(username)
    if found_user && found_user.is_password?(password)
       found_user
    else
       nil
    end
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
  
  
  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  
  private
  
  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end
  
  def logged_in?
    return false unless current_user
    session[:session_token] == current_user.session_token
  end
  
  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  
  before_filter :require_login
  
  def new
    @goal = Goal.new
    render :new    
  end

  def create
    @goal = current_user.goals.new(goal_params)
    
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end
  
  
  def index
    @goals = Goal.all
    render :index
  end

  def edit
    @goal = Goal.find(params[:id])
    if @goal
      render :edit
    else
      flash.now[:errors] = ["Invalid goal"]
      redirect_to goals_url
    end
  end
  
  def update
    @goal = Goal.find(params[:id])
    
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def show
    @goal = Goal.find_by_id(params[:id])
    render :show
  end
  
  def destroy
    goal = Goal.find(params[:id])
    if current_user.id == goal.user_id
      goal.destroy
    end
    redirect_to goals_url
  end
  
  private
  
  def goal_params
    params.require(:goal).permit(:name, :privacy, :completion)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end
  
  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    
    if @user
      login!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = ["Invalid Username/Password combination"]
      render :new
    end
  end
  
  def destroy
    log_out!
    redirect_to goals_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def authenticate
    "<input
        type=\"hidden\"
        name=\"authenticity_token\"
        value=\"#{form_authenticity_token}\">".html_safe
  end
  
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Goals#edit</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="put">
  <%= authenticate %>
  
  <input 
    type="hidden" 
    name="goal[completion]" 
    value="<%= @goal.completion || false %>">
  
  <label for="name"> Name </label>
  <input id="name" name="goal[name]" type="text", value="<%= @goal.name%>">
  
  <br>
  Private?
  <% [true, false].each do |el| %>
    <label for="priv"> <%= el %> </label>
    <input type="radio" id="priv"
               <%= "checked" if @goal.privacy == el %>
               name="goal[privacy]"
               value="<%= el %>"> 
  <% end %>
  
  <br>
  <button> Update Goal </button>
</form>

app/views/goals/index.html.erb
<h1>Goals Index</h1>

<% @goals.each do |goal| %>
  <%if ( !goal.privacy || (goal.user_id == current_user.id ) )%>
    <%=link_to goal.name, goal_url(goal) %>
  <% end %>
  <br>
<% end %>

<%= link_to "New Goal", new_goal_url %>

app/views/goals/new.html.erb
<h1>New Goal</h1>



<form action="<%= goals_url%>" method="post">
  <%= authenticate %>
  
  <input type="hidden" name="goal[completion]" value="false">
  
  <label for="name"> Name </label>
  <input id="name" name="goal[name]" type="text">
  
  <br>
  Private?
  <% [true, false].each do |el| %>
    <label for="priv-<%= el %>"> <%= el.to_s %> </label>
    <input type="radio" id="priv-<%= el %>" name="goal[privacy]" value="<%= el %>"> 
  <% end %>
  
  <br>
  <button> Create Goal </button>
</form>

app/views/goals/show.html.erb
<h1><%= @goal.name %></h1>

<h3> Completed? <%= @goal.completion %> </h3>

<br>

<h3> Private? <%= @goal.privacy %> </h3>

<%= link_to "Goal Index", goals_url%>

<%= link_to "Edit Goal", edit_goal_url(@goal)%>

<% if current_user.id == @goal.user_id %>
<%= button_to "Delete Goal", goal_url(@goal), method: :delete %>
<% end %>

<form action="<%= goal_url(@goal) %>" method="post">
  <%= authenticate %>
  <input type="hidden" name="_method" value="put">
  <input type="hidden" name="goal[completion]" value="true">
  <button> Goal Complete </button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? %>
<h3> Welcome <%= current_user.username %> </h3>
<% end %>


<% if flash[:errors]%>
  <% flash[:errors].each do |error|%>
    <%= error %>
  <% end %>
<% end %>

<%= yield %>


<br>
<br>
<% verb = (logged_in? ? "Sign Out" : "Sign In")%>
<% location = (logged_in? ? session_url : new_session_url )%>
<% action = (logged_in? ? :delete : :get)%>

<% unless request.original_url == new_session_url || request.original_url == session_url %>
  <%= button_to verb, location, method: action%>
<% end %>
</body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>

<form action="<%= users_url%>" method="post">
  <%= authenticate %>
  <label for="username"> Username </label>
  <input id="username" name="user[username]" type="text">
  
  <label for="password"> Password </label>
  <input id="password" name="user[password]" type="password">
  
  
  <button> Sign Up </button>
</form>